repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
    - id: black
      language_version: python3.11
    - id: black-jupyter
      language_version: python3.11

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8

# for isort use locally by runnig > isort . to correct all files imports
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
    - id: interrogate
      args: [-vv, -i, --fail-under=80]

# -   repo: local
#     hooks:
#     -   id: pylint
#         name: pylint
#         entry: pylint
#         language: system
#         types: [python]
#         args: [
#             "-rn", # Only display messages
#             "-sn", # Don't display the score
#             #"--recursive=y"
#         ]

-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [
            "tests/"
        ]
