stages:
  etl:
    cmd: python etl/etl.py
    deps:
      - data/raw/Chest_X_Ray/train
      - data/raw/Chest_X_Ray/val
      - data/raw/Chest_X_Ray/test
      - data/raw/Chest_X_Ray/dst
    params:
        - config/etl/etl1.yaml

  train:
    cmd: python ml/train.py
    deps:
      - data/raw/Chest_X_Ray/dst
    params:
        - config/ml/ml1.yaml
  test:
    cmd: pipenv run pytest tests/
