stages:
  etl:
    cmd: python etl/etl.py
    params:
        - config/etl/etl1.yaml:
    deps:
      - etl/etl.py
      - data/raw/Chest_X_Ray/train
      - data/raw/Chest_X_Ray/val
      - data/raw/Chest_X_Ray/test
    outs:
      - data/final
  train:
    cmd: python ml/tracking_train.py
    params:
        - config/ml/ml1.yaml:
    deps:
      - data/final
      - ml/train.py
    outs:
      - experiments/training_outputs
  test:
    cmd: pipenv run pytest tests/
