defaults:
  - _self_
  - etl: etl1
  - ml: ml1


mlflow_experiment_name: chest_disease_classification
model_dir_output: experiments/training_outputs
mlflow_tracking_uri: sqlite:///mlflow.db
dataset_dvc: data/Chest_X_Ray.dvc
data:
  path: data/raw/Chest_X_Ray
  path_dst: data/final
  train:
    name: train.csv
    path: data/raw/Chest_X_Ray/train
  val:
    name: val.csv
    path: data/raw/Chest_X_Ray/val
  test:
    name: test.csv
    path: data/raw/Chest_X_Ray/test
