
model_name: chest_diseases_pt_cnn
model_save_name: chest_diseases_pt_cnn.pt
model_architecture: mobilenetv2

params: {
    "model": model_architecture,
    "dataset_version": dataset_version,
    "seed": seed,
    "batch_size": 32,
    "num_workers": 8,
    "gpus": gpus,
    "precision": 32,
    "max_epochs": 25,
    "dropout": 0.2,
    "lr": 1e-1,
    "use_imagenet_pretrained_weights": use_imagenet_pretrained_weights,
    "early_stopping_patience": 3,
}
