name: ci-tests
on:
  push:
  pull_request:
    branches:
      - main
    paths:
      - './**'
env:
  AWS_DEFAULT_REGION: 'eu-north-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo
      #----------------------------------------------
      - uses: actions/checkout@v2

      #----------------------------------------------
      #       set-up python
      #----------------------------------------------
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      #----------------------------------------------
      #       set-up pipenv
      #----------------------------------------------
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      #----------------------------------------------
      #       install dependencies
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      #----------------------------------------------
      #       Pull from dvc
      #----------------------------------------------
      - name: Pull data from DVC
        run: |
          pipenv run dvc remote modify --local myremote access-key-id ${{env.AWS_ACCESS_KEY_ID}}
          pipenv run dvc remote modify --local myremote secret-access-key ${{env.AWS_SECRET_ACCESS_KEY}}
          pipenv run dvc pull --run-cache

      #----------------------------------------------
      #       Run Pipline
      #----------------------------------------------
      - name: Run the pipeline with DVC
        run: pipenv run dvc repro

      - name: Push the outcomes to DVC remote storage
        run: pipenv run dvc push
      #----------------------------------------------
      #       set environment
      #----------------------------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
