name: ci-tests
on: 
  push:
  pull_request:
    branches:
      - main
    paths:
      - './**'
env:
  AWS_DEFAULT_REGION: 'eu-north-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: "./"
        run: pip install poetry && poetry install

      - name: Run Unit tests
        working-directory: "./"
        run: poetry run pytest tests/

      # - name: Lint
      #   working-directory: "./"
        #run: poetry run pylint --recursive=y .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

   